dist: trusty
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add eslint
after_success: yarn coverage
